/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.JXTable;

/**
 *
 * @author Dheta
 */
public class ownerBarang extends javax.swing.JFrame {

    /**
     * Creates new form ownerBarang
     */
    public ownerBarang() {
        initComponents();
    }
    
    public void setID(String n){
         id.setText(n);
    } 
    
     public String getPencarianBarang() {
        return cari.getText();
    }

    public void setTabelBarang(DefaultTableModel t) {
        tabelBarang.setModel(t);
    }

    public void tabelListener(MouseListener m) {
        tabelBarang.addMouseListener(m);
    }

    public void tambahBarangListener(ActionListener a) {
        tambahBarang.addActionListener(a);
    }

    public void ubahBarangListener(ActionListener a) {
        ubah.addActionListener(a);
    }

    public void cariBarangListener(ActionListener a) {
        cariButton.addActionListener(a);
    }
   
    public void logoutListener(ActionListener a) {
        logout.addActionListener(a);
    }
    
      
    public void transaksiListener(ActionListener a) {
        transaksi.addActionListener(a);
    }

    public void karyawanListener(ActionListener a) {
        karyawan.addActionListener(a);
    }

    public void barangListener(ActionListener a) {
        barang.addActionListener(a);
    }
    public JButton barang(){
        return barang;
    }

    public void kembaliListener(ActionListener a) {
        ubah.addActionListener(a);
    }
    
    
    public void jenisListener(ActionListener a) {
        jenis.addActionListener(a);
    }

    public void merkListener(ActionListener a) {
        barang.addActionListener(a);
    }

    public JTable getTabelBarang() {
        return tabelBarang;
    }

    public int getJumlahBaris() {
        return tabelBarang.getRowCount();
    }

    public JButton getUbahBarang() {
        return ubah;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cari = new javax.swing.JTextField();
        ubah = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelBarang = new javax.swing.JTable();
        logout = new javax.swing.JButton();
        cariButton = new javax.swing.JButton();
        tambahBarang = new javax.swing.JButton();
        karyawan = new javax.swing.JButton();
        transaksi = new javax.swing.JButton();
        barang = new javax.swing.JButton();
        jenis = new javax.swing.JButton();
        merk = new javax.swing.JButton();
        id = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 240, -1));

        ubah.setText("ubah barang");
        getContentPane().add(ubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 190, 110, -1));

        tabelBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelBarang);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 510, 350));

        logout.setText("logout");
        getContentPane().add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 30, 80, -1));

        cariButton.setText("cari");
        getContentPane().add(cariButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, -1, -1));

        tambahBarang.setText("tambah barang");
        getContentPane().add(tambahBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 230, -1, -1));

        karyawan.setText("karyawan");
        getContentPane().add(karyawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 120, -1));

        transaksi.setText("transaksi");
        getContentPane().add(transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 120, -1));

        barang.setText("barang");
        getContentPane().add(barang, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 120, -1));

        jenis.setText("daftar jenis");
        getContentPane().add(jenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 280, 130, -1));

        merk.setText("daftar merk");
        getContentPane().add(merk, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 330, 130, -1));

        id.setText(" ");
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 30, 60, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dheta\\Documents\\NetBeansProjects\\silviana\\src\\view\\png\\02. owner barang.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ownerBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ownerBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ownerBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ownerBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ownerBarang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton barang;
    private javax.swing.JTextField cari;
    private javax.swing.JButton cariButton;
    private javax.swing.JLabel id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jenis;
    private javax.swing.JButton karyawan;
    private javax.swing.JButton logout;
    private javax.swing.JButton merk;
    private javax.swing.JTable tabelBarang;
    private javax.swing.JButton tambahBarang;
    private javax.swing.JButton transaksi;
    private javax.swing.JButton ubah;
    // End of variables declaration//GEN-END:variables
}
