/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import java.sql.Connection;
import javax.swing.JButton;
import javax.swing.JComboBox;
import model.barang;

/**
 *
 * @author Dheta
 */
public class ownerUbahBarang extends javax.swing.JFrame {

    /**
     * Creates new form ownerUbahBarang
     */
    Connection konek;
    barang modelBarang;
    String jenis_Barang[][];
    String merk_Barang[][];

    /**
     * Creates new form ownerBarangTambah
     */
    public ownerUbahBarang() {
        modelBarang = new barang();
        jenisBarang = new JComboBox();
        merkBarang = new JComboBox();

        jenis_Barang = modelBarang.getJenis();
        merk_Barang = modelBarang.getMerk();
        initComponents();
    }

     public void setNamaBarang(String teks) {
        namaBarang.setText(teks);
    }

    public void setHargaBarang(int teks) {
        System.out.println(teks);
        hargaBarang.setText("" + teks);
    }

    public void setStokBarang(int stok) {
        stokBarang.setValue(stok);
    }
    
    public void setID(String k){
        id.setText(k);
    }
    
    public JComboBox<String> setJenisBarang() {
        return jenisBarang;
    }

    public JComboBox<String> setJMerkBarang() {
        return merkBarang;
    }

    
    public String getJenis() {
        int indeks = jenisBarang.getSelectedIndex();
        return jenis_Barang[1][indeks];
    }

    public String getMerk() {
        int indeks = merkBarang.getSelectedIndex();
        return merk_Barang[0][indeks];
    }

    public String getHargaBarang() {
        return hargaBarang.getText();
    }

    public String getNamaBarang() {
        return namaBarang.getText();
    }

    public String getStokBarang() {
        String stok = stokBarang.getModel().getValue().toString();
        return stok;
    }

    public void inputListener(ActionListener a) {
        simpan.addActionListener(a);
    }
    
    public void logoutListener(ActionListener a) {
        logout.addActionListener(a);
    }

    public void kembaliListener(ActionListener a) {
        kembali.addActionListener(a);
    }

    public void jenisListener(ActionListener a) {
        tambahJenis.addActionListener(a);
    }

    public void merkListener(ActionListener a) {
        tambahMerk.addActionListener(a);
    }
    
    public void transaksiListener(ActionListener a) {
        transaksi.addActionListener(a);
    }

    public void karyawanListener(ActionListener a) {
        karyawan.addActionListener(a);
    }

    public void barangListener(ActionListener a) {
        barang.addActionListener(a);
    }
    public JButton barang(){
        return barang;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        merkBarang = new javax.swing.JComboBox(merk_Barang[1]);
        simpan = new javax.swing.JButton();
        kembali = new javax.swing.JButton();
        tambahMerk = new javax.swing.JButton();
        tambahJenis = new javax.swing.JButton();
        jenisBarang = new javax.swing.JComboBox(jenis_Barang[0]);
        hargaBarang = new javax.swing.JTextField();
        stokBarang = new javax.swing.JSpinner();
        namaBarang = new javax.swing.JTextField();
        logout = new javax.swing.JButton();
        karyawan = new javax.swing.JButton();
        transaksi = new javax.swing.JButton();
        barang = new javax.swing.JButton();
        id = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        getContentPane().add(merkBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 130, -1));

        simpan.setText("simpan");
        getContentPane().add(simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 460, -1, -1));

        kembali.setText("kembali");
        getContentPane().add(kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 450, -1, -1));

        tambahMerk.setText("tambah merk");
        getContentPane().add(tambahMerk, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 280, -1, -1));

        tambahJenis.setText("tambah jenis");
        getContentPane().add(tambahJenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 220, -1, -1));

        jenisBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisBarangActionPerformed(evt);
            }
        });
        getContentPane().add(jenisBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 130, 20));
        getContentPane().add(hargaBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, 120, -1));
        getContentPane().add(stokBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, 110, -1));
        getContentPane().add(namaBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 120, -1));

        logout.setText("logout");
        getContentPane().add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 40, 120, -1));

        karyawan.setText("karyawan");
        getContentPane().add(karyawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 120, -1));

        transaksi.setText("transaksi");
        getContentPane().add(transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 120, -1));

        barang.setText("barang");
        getContentPane().add(barang, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 120, -1));
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 50, 70, 20));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/png/03. owner tambah barang.png"))); // NOI18N
        jLabel6.setText(" ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jenisBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jenisBarangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ownerUbahBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ownerUbahBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ownerUbahBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ownerUbahBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ownerUbahBarang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton barang;
    private javax.swing.JTextField hargaBarang;
    private javax.swing.JLabel id;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JComboBox<String> jenisBarang;
    private javax.swing.JButton karyawan;
    private javax.swing.JButton kembali;
    private javax.swing.JButton logout;
    private javax.swing.JComboBox<String> merkBarang;
    private javax.swing.JTextField namaBarang;
    private javax.swing.JButton simpan;
    private javax.swing.JSpinner stokBarang;
    private javax.swing.JButton tambahJenis;
    private javax.swing.JButton tambahMerk;
    private javax.swing.JButton transaksi;
    // End of variables declaration//GEN-END:variables
}
