/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import java.sql.Connection;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import model.barang;
import model.user;
import org.jdesktop.swingx.JXTable;

/**
 *
 * @author Dheta
 */
public class ownerDashboard extends javax.swing.JFrame {

    Connection konek;
    barang modelBarang;
    user modelUser;
    String jenis_barang[][];
    String merk_barang[][];
    String nama_barang[][];
    DateFormat date;

    /**
     * Creates new form ownerDashboard
     */
    public ownerDashboard() {
        modelBarang = new barang();
        jenisBarang = new JComboBox();
        merkBarang = new JComboBox();
        namaBarang = new JComboBox();

        jenis_barang = modelBarang.getJenis();
        merk_barang = modelBarang.getMerk();
        date = new SimpleDateFormat("yyyy-MM-dd");
        this.date = DateFormat.getDateInstance();
        initComponents();
    }

    public Date gettglBeli() {
        Date tgllahir1 = (calender.getDate());
        return tgllahir1;
    }

    public JLabel getIDLK() {
        return pegawai;
    }

    public String getID() {
        return pegawai.getText();
    }

    public void setID(String id) {
        this.pegawai.setText(id);
    }

    public String getJenis() {
        int indeks = jenisBarang.getSelectedIndex();
        return jenis_barang[1][indeks];
    }

    public String getMerk() {
        int indeks = merkBarang.getSelectedIndex();
        return merk_barang[0][indeks];
    }

    public String getBarang() {
        int indeks = namaBarang.getSelectedIndex();
        return nama_barang[0][indeks];
    }

    public void setTabelPembayaran(DefaultTableModel t) {
        tabelTransaksi.setModel(t);
    }

    public void addTableListener(MouseListener listener) {
        tabelTransaksi.addMouseListener(listener);
    }

    public void logoutListener(ActionListener a) {
        logout.addActionListener(a);
    }

    public void transaksiListener(ActionListener a) {
        transaksi.addActionListener(a);
    }

    public void karyawanListener(ActionListener a) {
        karyawan.addActionListener(a);
    }

    public void barangListener(ActionListener a) {
        barang.addActionListener(a);
    }

    public void eksportListener(ActionListener a) {
        eksport.addActionListener(a);
    }

    public JButton kal() {
        return sortDate;
    }

    public JButton month() {
        return sortMonth;
    }

    public JButton detail() {
        return eksport;
    }

    public JTable tabel() {
        return tabelTransaksi;
    }

    public void kalender(ActionListener a) {
        sortDate.addActionListener(a);
    }

    public void tabelListener(MouseListener a) {
        tabelTransaksi.addMouseListener(a);
    }

    public void kalender2(ActionListener a) {
        sortMonth.addActionListener(a);
    }

    public void kalender3(ActionListener a) {
        calender.addActionListener(a);
    }

    public void sortByNama(ActionListener a) {
        namaBarang.addActionListener(a);
    }

    public void reset(ActionListener a) {
        reset.addActionListener(a);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sortMonth = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        sortDate = new javax.swing.JButton();
        namaBarang = new javax.swing.JComboBox();
        jenisBarang = new javax.swing.JComboBox(jenis_barang[0]);
        merkBarang = new javax.swing.JComboBox(this.merk_barang[1]);
        reset = new javax.swing.JButton();
        transaksi = new javax.swing.JButton();
        eksport = new javax.swing.JButton();
        calender = new org.jdesktop.swingx.JXDatePicker();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelTransaksi = new javax.swing.JTable();
        karyawan = new javax.swing.JButton();
        barang = new javax.swing.JButton();
        pegawai = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sortMonth.setText("sort by month");
        getContentPane().add(sortMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, -1, -1));

        logout.setText("keluar");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        getContentPane().add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 460, -1, -1));

        sortDate.setText("sort by date");
        getContentPane().add(sortDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, -1, -1));

        namaBarang.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(namaBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 250, 140, -1));

        jenisBarang.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jenisBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisBarangActionPerformed(evt);
            }
        });
        getContentPane().add(jenisBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, 140, -1));

        merkBarang.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        merkBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                merkBarangActionPerformed(evt);
            }
        });
        getContentPane().add(merkBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, 140, -1));

        reset.setText("reset");
        getContentPane().add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 45, -1, -1));

        transaksi.setText("transaksi");
        getContentPane().add(transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 370, 120, -1));

        eksport.setText("detail transaksi");
        getContentPane().add(eksport, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 430, -1, -1));

        calender.setBackground(new java.awt.Color(153, 153, 153));
        calender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calenderActionPerformed(evt);
            }
        });
        getContentPane().add(calender, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, 180, -1));

        tabelTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabelTransaksi);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        karyawan.setText("karyawan");
        getContentPane().add(karyawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 340, 120, -1));

        barang.setText("barang");
        getContentPane().add(barang, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 400, 120, -1));
        getContentPane().add(pegawai, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, 70, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutActionPerformed

    private void calenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calenderActionPerformed

    private void jenisBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisBarangActionPerformed
        int jenisBarang1 = jenisBarang.getSelectedIndex();
        int merkBarang1 = merkBarang.getSelectedIndex();
        System.out.println(jenisBarang1);
        System.out.println(merkBarang1);
        nama_barang = modelBarang.getNamaBarangPilihan(jenis_barang[1][jenisBarang1], merk_barang[0][merkBarang1]);
        namaBarang.setModel(new DefaultComboBoxModel<>(nama_barang[1]));        // TODO add your handling code here:

    }//GEN-LAST:event_jenisBarangActionPerformed

    private void merkBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_merkBarangActionPerformed
        int jenisBarang1 = jenisBarang.getSelectedIndex();
        int merkBarang1 = merkBarang.getSelectedIndex();
        System.out.println(jenisBarang1);
        System.out.println(merkBarang1);
        nama_barang = modelBarang.getNamaBarangPilihan(jenis_barang[1][jenisBarang1], merk_barang[0][merkBarang1]);
        namaBarang.setModel(new DefaultComboBoxModel<>(nama_barang[1]));        // TODO add your handling code here:
    }//GEN-LAST:event_merkBarangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ownerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ownerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ownerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ownerDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ownerDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton barang;
    private org.jdesktop.swingx.JXDatePicker calender;
    private javax.swing.JButton eksport;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox jenisBarang;
    private javax.swing.JButton karyawan;
    private javax.swing.JButton logout;
    private javax.swing.JComboBox merkBarang;
    private javax.swing.JComboBox namaBarang;
    private javax.swing.JLabel pegawai;
    private javax.swing.JButton reset;
    private javax.swing.JButton sortDate;
    private javax.swing.JButton sortMonth;
    private javax.swing.JTable tabelTransaksi;
    private javax.swing.JButton transaksi;
    // End of variables declaration//GEN-END:variables
}
